defaults: &defaults
  reference_repository_path: ~/.g5kapi/reference-repository
  reference_repository_path_prefix: data
  base_uri: https://api.grid5000.fr

development:
  <<: *defaults

test:
  <<: *defaults
  reference_repository_path: spec/fixtures/reference-repository

production:
  <<: *defaults