defaults: &defaults
  logger_level: DEBUG
  tmp_path: /tmp
  header_user_cn: X-Api-User-CN
  reference_repository_path: /var/db/g5kapi/reference-repository
  reference_repository_path_prefix: data/grid5000
  base_uri_in: https://api.grid5000.fr
  base_uri_out: http://localhost:8888
  kadeploy_uri: druby://kadeploy-server:25300
  oar: &oar
    adapter: em_mysqlplus
    encoding: utf8
    pool: 200
    timeout: 5000
    database: oar2
    host: mysql
    port: 3306
    username: oarreader
    password:
    
development:
  <<: *defaults
  base_uri_in: http://localhost:8000
  base_uri_out: http://localhost:8000
  kadeploy_uri: druby://localhost:25300
  notifications_uri: https://localhost:3443/sid/notifications
  reference_repository_path: ~/dev/g5k-api/reference-repository
  oar:
    <<: *oar
    host: 127.0.0.1
    port: 13306

test:
  <<: *defaults
  base_uri_in: http://api-in.local
  base_uri_out: http://api-out.local
  reference_repository_path: spec/fixtures/reference-repository
  notifications_uri: http://fake.api/sid/notifications
  oar:
    <<: *oar
    host: 127.0.0.1
    port: 3306
    username: root
    password:
    

production:
  <<: *defaults
  notifications_uri: http://localhost:8888/sid/notifications
  