defaults: &defaults
  reference_repository_path: ~/.g5kapi/reference-repository
  reference_repository_path_prefix: data
  base_uri_in: https://api.grid5000.fr
  base_uri_out: http://localhost:8888
  oar: &oar
    adapter: em_mysqlplus
    encoding: utf8
    pool: 200
    timeout: 5000
    database: oar2
    host: mysql
    port: 3306
    username: oarreader
    password:
    
development:
  <<: *defaults
  base_uri_in: http://localhost:3000
  base_uri_out: http://localhost:3000
  oar:
    <<: *oar
    host: 127.0.0.1
    port: 13306

test:
  <<: *defaults
  base_uri_in: http://api-in.local
  base_uri_out: http://api-out.local
  reference_repository_path: spec/fixtures/reference-repository
  oar:
    <<: *oar
    host: 127.0.0.1
    port: 3306
    username: root
    password:
    

production:
  <<: *defaults